//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfPais
{
    using System;
    using System.Collections.Generic;
    
    public partial class pais
    {
        public pais()
        {
            this.departamento = new HashSet<departamento>();
        }
    
        public int id { get; set; }
        public string pais1 { get; set; }
    
        public virtual ICollection<departamento> departamento { get; set; }
    }
}
