//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfPais
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int cod_p { get; set; }
        public string ci { get; set; }
        public string nombres { get; set; }
        public string ap_pat { get; set; }
        public string ap_mat { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
