//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfPais
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id { get; set; }
        public Nullable<int> cod_p { get; set; }
        public string usuario1 { get; set; }
        public string clave { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public Nullable<int> cargo { get; set; }
    
        public virtual cargo cargo1 { get; set; }
        public virtual persona persona { get; set; }
    }
}
